# Generated by Django 5.1.1 on 2026-06-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(db_index=True, default='English', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(db_index=True, decimal_places=1, max_digits=3),
        ),
    ]
